package co.edu.uniquindio.compiladores

enum class Categoria {
    ENTERO,
    DECIMAL,
    IDENTIFICADOR,
    OPERADOR_LOGICO,
    PARENTESIS_IZQUIERDO,
    COMENTARIO,
    COMENTARIO_BLOQUE,
    DESCONOCIDO,
    METODO,
    TRUE,
    CARACTER,
    CADENA,
    CLASE,
    PALABRA_RESERVADA,
    LLAVE,
    AGRUPADOR,
    OP_CONCATENACION,
    OP_ARITMETICO,
    OP_RELACIONAL,
    OP_ASIGNACION,
    SEPARADOR,
    REAL,
    VARIABLE,
    INCREMENTO,
    DECREMENTO
}